# Generated by Django 6.0.1 on 2026-01-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="Código DANE"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoEntidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CAMARA_COMERCIO", "Cámara de Comercio"),
                            ("RUT", "RUT"),
                            ("CEDULA_RL", "Cédula Representante Legal"),
                            ("RESOLUCION_HAB", "Resolución de Habilitación"),
                            ("LICENCIA_SANITARIA", "Licencia Sanitaria"),
                            ("POLIZA_RC", "Póliza de Responsabilidad Civil"),
                            ("CERTIFICADO_PARAFISCALES", "Certificado de Parafiscales"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del documento"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="entidades/documentos/", verbose_name="Archivo"
                    ),
                ),
                (
                    "fecha_expedicion",
                    models.DateField(verbose_name="Fecha de expedición"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de vencimiento"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de subida"
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Entidad",
                "verbose_name_plural": "Documentos de Entidad",
                "ordering": ["entidad", "tipo", "-fecha_expedicion"],
            },
        ),
        migrations.CreateModel(
            name="EntidadPrestadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=300, verbose_name="Razón social"),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Nombre comercial"
                    ),
                ),
                (
                    "nit",
                    models.CharField(max_length=20, unique=True, verbose_name="NIT"),
                ),
                (
                    "digito_verificacion",
                    models.CharField(
                        max_length=1, verbose_name="Dígito de verificación"
                    ),
                ),
                (
                    "codigo_reps",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Código REPS",
                    ),
                ),
                (
                    "representante_legal",
                    models.CharField(
                        max_length=200, verbose_name="Representante legal"
                    ),
                ),
                (
                    "documento_representante",
                    models.CharField(
                        max_length=20, verbose_name="Documento representante"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=300, verbose_name="Dirección"),
                ),
                ("telefono", models.CharField(max_length=50, verbose_name="Teléfono")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                ("sitio_web", models.URLField(blank=True, verbose_name="Sitio web")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="entidades/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "gerente",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Gerente/Director"
                    ),
                ),
                (
                    "responsable_calidad",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Responsable de calidad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("EN_PROCESO", "En proceso de habilitación"),
                        ],
                        default="EN_PROCESO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_inscripcion_reps",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha inscripción REPS"
                    ),
                ),
                (
                    "fecha_vencimiento_habilitacion",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha vencimiento habilitación",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entidad Prestadora",
                "verbose_name_plural": "Entidades Prestadoras",
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=5, unique=True, verbose_name="Código DANE"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
                "ordering": ["departamento__nombre", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre de la sede"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRINCIPAL", "Sede Principal"),
                            ("SECUNDARIA", "Sede Secundaria"),
                            ("AMBULANCIA", "Base de ambulancia"),
                            ("MOVIL", "Unidad móvil"),
                        ],
                        default="SECUNDARIA",
                        max_length=20,
                        verbose_name="Tipo de sede",
                    ),
                ),
                (
                    "codigo_reps_sede",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Código REPS Sede"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=300, verbose_name="Dirección"),
                ),
                ("telefono", models.CharField(max_length=50, verbose_name="Teléfono")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Director/Coordinador"
                    ),
                ),
                (
                    "responsable_sede",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Responsable de la sede",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(default=True, verbose_name="Sede activa"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "ordering": ["entidad", "tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ServicioHabilitado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complejidad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                        ],
                        max_length=10,
                        verbose_name="Complejidad",
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("INTRAMURAL", "Intramural"),
                            ("EXTRAMURAL", "Extramural"),
                            (
                                "TELEMEDICINA_REMISOR",
                                "Telemedicina - Prestador Remisor",
                            ),
                            (
                                "TELEMEDICINA_REFERENCIA",
                                "Telemedicina - Prestador de Referencia",
                            ),
                        ],
                        default="INTRAMURAL",
                        max_length=30,
                        verbose_name="Modalidad",
                    ),
                ),
                (
                    "fecha_habilitacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de habilitación"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
            ],
            options={
                "verbose_name": "Servicio Habilitado",
                "verbose_name_plural": "Servicios Habilitados",
                "ordering": ["sede", "servicio"],
            },
        ),
        migrations.CreateModel(
            name="TipoPrestador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=10, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de Prestador",
                "verbose_name_plural": "Tipos de Prestador",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="VigenciaHabilitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin")),
                (
                    "numero_resolucion",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de resolución"
                    ),
                ),
                (
                    "fecha_resolucion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de resolución"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("VENCIDA", "Vencida"),
                            ("SUSPENDIDA", "Suspendida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ACTIVA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "porcentaje_cumplimiento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Porcentaje de cumplimiento",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vigencia de Habilitación",
                "verbose_name_plural": "Vigencias de Habilitación",
                "ordering": ["entidad", "-fecha_inicio"],
            },
        ),
    ]
