# Generated by Django 6.0.1 on 2026-01-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
        ("estandares", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoentidad",
            name="subido_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_subidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entidadprestadora",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entidades_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entidadprestadora",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entidades.departamento",
                verbose_name="Departamento",
            ),
        ),
        migrations.AddField(
            model_name="documentoentidad",
            name="entidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="entidades.entidadprestadora",
                verbose_name="Entidad",
            ),
        ),
        migrations.AddField(
            model_name="municipio",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="municipios",
                to="entidades.departamento",
            ),
        ),
        migrations.AddField(
            model_name="entidadprestadora",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entidades.municipio",
                verbose_name="Municipio",
            ),
        ),
        migrations.AddField(
            model_name="sede",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entidades.departamento",
                verbose_name="Departamento",
            ),
        ),
        migrations.AddField(
            model_name="sede",
            name="entidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sedes",
                to="entidades.entidadprestadora",
                verbose_name="Entidad",
            ),
        ),
        migrations.AddField(
            model_name="sede",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entidades.municipio",
                verbose_name="Municipio",
            ),
        ),
        migrations.AddField(
            model_name="serviciohabilitado",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicios_habilitados",
                to="entidades.sede",
                verbose_name="Sede",
            ),
        ),
        migrations.AddField(
            model_name="serviciohabilitado",
            name="servicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sedes_habilitadas",
                to="estandares.servicio",
                verbose_name="Servicio",
            ),
        ),
        migrations.AddField(
            model_name="entidadprestadora",
            name="tipo_prestador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entidades.tipoprestador",
                verbose_name="Tipo de prestador",
            ),
        ),
        migrations.AddField(
            model_name="vigenciahabilitacion",
            name="entidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vigencias",
                to="entidades.entidadprestadora",
                verbose_name="Entidad",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sede",
            unique_together={("entidad", "codigo_reps_sede")},
        ),
        migrations.AlterUniqueTogether(
            name="serviciohabilitado",
            unique_together={("sede", "servicio", "modalidad")},
        ),
    ]
