# Generated by Django 6.0.1 on 2026-01-14 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0002_initial"),
        ("estandares", "0002_servicio_es_obligatorio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_activacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de activación"
                    ),
                ),
                (
                    "activado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicios_activados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_evaluacion",
                        to="entidades.entidadprestadora",
                        verbose_name="Entidad",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_entidad",
                        to="estandares.servicio",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Evaluación",
                "verbose_name_plural": "Configuraciones de Evaluación",
                "ordering": ["entidad", "servicio__codigo"],
                "unique_together": {("entidad", "servicio")},
            },
        ),
    ]
