# Generated by Django 4.2.25 on 2026-01-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("estandares", "0002_servicio_es_obligatorio"),
        ("entidades", "0003_configuracionevaluacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionEvaluacionSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_activacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de activación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "activado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grupos_activados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grupo_estandar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_sede",
                        to="estandares.grupoestandar",
                        verbose_name="Grupo de Estándares",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_evaluacion",
                        to="entidades.sede",
                        verbose_name="Sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Evaluación por Sede",
                "verbose_name_plural": "Configuraciones de Evaluación por Sede",
                "ordering": ["sede", "grupo_estandar__orden"],
                "unique_together": {("sede", "grupo_estandar")},
            },
        ),
        migrations.DeleteModel(
            name="ConfiguracionEvaluacion",
        ),
    ]
