# Generated by Django 4.2.25 on 2026-01-19 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("estandares", "0003_tipo_criterio"),
        ("entidades", "0004_cambio_evaluacion_sede"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionEstandarSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_activacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de activación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "activado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estandares_activados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estandar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_sede",
                        to="estandares.estandar",
                        verbose_name="Estándar",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_estandar",
                        to="entidades.sede",
                        verbose_name="Sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Estándar por Sede",
                "verbose_name_plural": "Configuraciones de Estándar por Sede",
                "ordering": ["sede", "estandar__grupo__orden", "estandar__orden"],
                "unique_together": {("sede", "estandar")},
            },
        ),
    ]
