# Generated by Django 6.0.1 on 2026-01-25 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngresoAgregado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ingreso Agregado",
                "verbose_name_plural": "Ingresos Agregados",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="OrganoEjecutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Órgano Ejecutor",
                "verbose_name_plural": "Órganos Ejecutores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Ingreso",
                "verbose_name_plural": "Tipos de Ingreso",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Vigencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(unique=True, verbose_name="Año")),
                (
                    "activa",
                    models.BooleanField(default=False, verbose_name="Vigencia Activa"),
                ),
                ("fecha_apertura", models.DateField(verbose_name="Fecha de Apertura")),
                (
                    "fecha_cierre",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Cierre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vigencia",
                "verbose_name_plural": "Vigencias",
                "ordering": ["-ano"],
            },
        ),
        migrations.CreateModel(
            name="FuenteFinanciacion",
            fields=[],
            options={
                "verbose_name": "Fuente de Financiación",
                "verbose_name_plural": "Fuentes de Financiación",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("planfinanciero.ingresoagregado",),
        ),
        migrations.CreateModel(
            name="Rubro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único del rubro (ej: 0301 - 1.1.01.01.100.01 - 14)",
                        max_length=100,
                        unique=True,
                        verbose_name="Código Presupuestal",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=500, verbose_name="Concepto del Ingreso"
                    ),
                ),
                (
                    "es_totalizador",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, es un rubro padre que agrupa otros rubros",
                        verbose_name="Es Totalizador",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Administración Central"),
                            ("EP", "Establecimientos Públicos"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "clase_ingreso",
                    models.CharField(
                        blank=True,
                        choices=[("CORRIENTE", "Corriente"), ("CAPITAL", "Capital")],
                        max_length=20,
                        null=True,
                        verbose_name="Clase de Ingreso",
                    ),
                ),
                (
                    "codigo_fuente",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código Fuente"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rubros_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingreso_agregado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rubros",
                        to="planfinanciero.ingresoagregado",
                        verbose_name="Ingreso Agregado",
                    ),
                ),
                (
                    "organo_ejecutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rubros",
                        to="planfinanciero.organoejecutor",
                        verbose_name="Órgano Ejecutor",
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hijos",
                        to="planfinanciero.rubro",
                        verbose_name="Rubro Padre",
                    ),
                ),
                (
                    "tipo_ingreso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rubros",
                        to="planfinanciero.tipoingreso",
                        verbose_name="Tipo de Ingreso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubro Presupuestal",
                "verbose_name_plural": "Rubros Presupuestales",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de Operación")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INICIAL", "Presupuesto Inicial"),
                            ("ADICION", "Adición"),
                            ("REDUCCION", "Reducción"),
                            ("TRASLADO_CREDITO", "Traslado (Crédito)"),
                            ("TRASLADO_DEBITO", "Traslado (Débito)"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "documento_soporte",
                    models.CharField(
                        help_text="Número de Ordenanza, Decreto o Acto Administrativo",
                        max_length=200,
                        verbose_name="Documento Soporte",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Valor (COP)"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "numero_ajuste",
                    models.IntegerField(
                        default=0,
                        help_text="0 para inicial, 1 para ajuste #1, etc.",
                        verbose_name="Número de Ajuste",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("anulado", models.BooleanField(default=False, verbose_name="Anulado")),
                (
                    "motivo_anulacion",
                    models.TextField(blank=True, verbose_name="Motivo de Anulación"),
                ),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_anulados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movimiento_relacionado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_relacionados",
                        to="planfinanciero.movimiento",
                        verbose_name="Movimiento Relacionado",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="planfinanciero.rubro",
                        verbose_name="Rubro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento",
                "verbose_name_plural": "Movimientos",
                "ordering": ["-fecha", "-fecha_registro"],
            },
        ),
    ]
