# Generated by Django 4.2.25 on 2026-01-25 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planfinanciero", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RubroGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("FUNCIONAMIENTO", "Funcionamiento"),
                            ("DEUDA", "Deuda"),
                            ("INVERSION", "Inversión"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Rubro",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rubro de Gasto",
                "verbose_name_plural": "Rubros de Gastos",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de Operación")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INICIAL", "Presupuesto Inicial"),
                            ("ADICION", "Adición"),
                            ("REDUCCION", "Reducción"),
                            ("CREDITO", "Crédito"),
                            ("CONTRACREDITO", "Contracrédito"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "documento_soporte",
                    models.CharField(
                        help_text="Número de Ordenanza, Decreto o Acto Administrativo",
                        max_length=200,
                        verbose_name="Documento Soporte",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Valor (COP)"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("anulado", models.BooleanField(default=False, verbose_name="Anulado")),
                (
                    "motivo_anulacion",
                    models.TextField(blank=True, verbose_name="Motivo de Anulación"),
                ),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_gasto_anulados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_gasto_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="planfinanciero.rubrogasto",
                        verbose_name="Rubro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Gasto",
                "verbose_name_plural": "Movimientos de Gastos",
                "ordering": ["-fecha", "-fecha_registro"],
            },
        ),
    ]
