# Generated by Django 4.2.25 on 2026-01-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planfinanciero", "0002_add_gastos_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rubrogasto",
            options={
                "ordering": ["tipo_entidad", "codigo"],
                "verbose_name": "Rubro de Gasto",
                "verbose_name_plural": "Rubros de Gastos",
            },
        ),
        migrations.AddField(
            model_name="rubrogasto",
            name="tipo_entidad",
            field=models.CharField(
                choices=[
                    ("CENTRALIZADO", "Centralizado"),
                    ("DESCENTRALIZADO", "Descentralizado"),
                ],
                default="CENTRALIZADO",
                max_length=20,
                verbose_name="Tipo de Entidad",
            ),
        ),
        migrations.AlterField(
            model_name="rubrogasto",
            name="codigo",
            field=models.CharField(max_length=30, verbose_name="Código Rubro"),
        ),
        migrations.AlterUniqueTogether(
            name="rubrogasto",
            unique_together={("tipo_entidad", "codigo")},
        ),
    ]
