# Generated by Django 6.0.1 on 2026-01-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncuestaSatisfaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "calificacion_general",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Calificación general",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(blank=True, verbose_name="Comentarios"),
                ),
            ],
            options={
                "verbose_name": "Encuesta de Satisfacción",
                "verbose_name_plural": "Encuestas de Satisfacción",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="PQRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PETICION", "Petición"),
                            ("QUEJA", "Queja"),
                            ("RECLAMO", "Reclamo"),
                            ("SUGERENCIA", "Sugerencia"),
                            ("FELICITACION", "Felicitación"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "radicado",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de radicado"
                    ),
                ),
                (
                    "nombre_solicitante",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del solicitante"
                    ),
                ),
                (
                    "documento_solicitante",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Documento"
                    ),
                ),
                (
                    "telefono_solicitante",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email_solicitante",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("asunto", models.CharField(max_length=300, verbose_name="Asunto")),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "archivo_adjunto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="siau/pqrs/",
                        verbose_name="Archivo adjunto",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RECIBIDA", "Recibida"),
                            ("EN_PROCESO", "En Proceso"),
                            ("RESPONDIDA", "Respondida"),
                            ("CERRADA", "Cerrada"),
                        ],
                        default="RECIBIDA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_radicacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de radicación"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha de vencimiento respuesta"),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de respuesta"
                    ),
                ),
                ("respuesta", models.TextField(blank=True, verbose_name="Respuesta")),
            ],
            options={
                "verbose_name": "PQRS",
                "verbose_name_plural": "PQRS",
                "ordering": ["-fecha_radicacion"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionSIAU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefono_atencion",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono de atención"
                    ),
                ),
                (
                    "email_atencion",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de atención"
                    ),
                ),
                (
                    "horario_atencion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Horario de atención"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="SIAU activo"),
                ),
                (
                    "entidad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_siau",
                        to="entidades.entidadprestadora",
                        verbose_name="Entidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración SIAU",
                "verbose_name_plural": "Configuraciones SIAU",
            },
        ),
    ]
