# Generated by Django 6.0.1 on 2026-01-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0002_initial"),
        ("estandares", "0001_initial"),
        ("siau", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionsiau",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="siau_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="entidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encuestas",
                to="entidades.entidadprestadora",
                verbose_name="Entidad",
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encuestas",
                to="entidades.sede",
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="estandares.servicio",
            ),
        ),
        migrations.AddField(
            model_name="pqrs",
            name="entidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pqrs",
                to="entidades.entidadprestadora",
                verbose_name="Entidad",
            ),
        ),
        migrations.AddField(
            model_name="pqrs",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pqrs_asignadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pqrs",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pqrs",
                to="entidades.sede",
            ),
        ),
    ]
