# Generated by Django 6.0.1 on 2026-01-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key_personalizada",
                    models.CharField(
                        blank=True,
                        help_text="API Key propia de la entidad (opcional, si no usa la global)",
                        max_length=200,
                        verbose_name="API Key personalizada",
                    ),
                ),
                (
                    "modelo_preferido",
                    models.CharField(
                        default="gpt-4o",
                        help_text="Modelo de OpenAI a utilizar",
                        max_length=50,
                        verbose_name="Modelo preferido",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=4000, verbose_name="Máximo de tokens"
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.7,
                        help_text="Controla la creatividad (0.0 = conservador, 1.0 = creativo)",
                        max_digits=2,
                        verbose_name="Temperatura",
                    ),
                ),
                (
                    "prompt_sistema",
                    models.TextField(
                        blank=True,
                        default="Eres un experto en habilitación de servicios de salud en Colombia, especializado en la Resolución 3100 de 2019. Ayudas a las instituciones a generar documentos que cumplan con los estándares de habilitación.",
                        verbose_name="Prompt del sistema",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="IA activa")),
            ],
            options={
                "verbose_name": "Configuración de IA",
                "verbose_name_plural": "Configuraciones de IA",
            },
        ),
        migrations.CreateModel(
            name="NormativaReferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RESOLUCION", "Resolución"),
                            ("LEY", "Ley"),
                            ("DECRETO", "Decreto"),
                            ("CIRCULAR", "Circular"),
                            ("GUIA", "Guía"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("numero", models.CharField(max_length=50, verbose_name="Número")),
                ("anio", models.PositiveIntegerField(verbose_name="Año")),
                ("titulo", models.CharField(max_length=300, verbose_name="Título")),
                (
                    "entidad_emisora",
                    models.CharField(max_length=200, verbose_name="Entidad emisora"),
                ),
                (
                    "fecha_expedicion",
                    models.DateField(verbose_name="Fecha de expedición"),
                ),
                ("vigente", models.BooleanField(default=True, verbose_name="Vigente")),
                ("resumen", models.TextField(blank=True, verbose_name="Resumen")),
                (
                    "contenido_completo",
                    models.TextField(
                        blank=True,
                        help_text="Texto completo de la norma para referencia de la IA",
                        verbose_name="Contenido completo",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="normatividad/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "url_oficial",
                    models.URLField(blank=True, verbose_name="URL oficial"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Normativa de Referencia",
                "verbose_name_plural": "Normativas de Referencia",
                "ordering": ["-anio", "numero"],
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("GENERAR", "Generar documento"),
                            ("MEJORAR", "Mejorar documento existente"),
                            ("REVISAR", "Revisar y corregir"),
                            ("ADAPTAR", "Adaptar normatividad"),
                            ("RESUMIR", "Resumir contenido"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="Usa {variables} para campos dinámicos como {criterio}, {entidad}, {servicio}",
                        verbose_name="Prompt",
                    ),
                ),
                (
                    "es_global",
                    models.BooleanField(
                        default=True,
                        help_text="Si es global, está disponible para todas las entidades",
                        verbose_name="Es global",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Prompt",
                "verbose_name_plural": "Plantillas de Prompts",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_enviado", models.TextField(verbose_name="Prompt enviado")),
                ("respuesta", models.TextField(blank=True, verbose_name="Respuesta")),
                (
                    "modelo_usado",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Modelo usado"
                    ),
                ),
                (
                    "tokens_prompt",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tokens del prompt"
                    ),
                ),
                (
                    "tokens_respuesta",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tokens de respuesta"
                    ),
                ),
                (
                    "tokens_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tokens totales"
                    ),
                ),
                (
                    "costo_estimado",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="Costo estimado USD",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROCESANDO", "Procesando"),
                            ("COMPLETADA", "Completada"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "mensaje_error",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de solicitud"
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de respuesta"
                    ),
                ),
                (
                    "tiempo_procesamiento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Tiempo de procesamiento (segundos)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de IA",
                "verbose_name_plural": "Solicitudes de IA",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
