# Generated by Django 6.0.1 on 2026-01-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documentos", "0001_initial"),
        ("entidades", "0001_initial"),
        ("estandares", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionia",
            name="entidad",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_ia",
                to="entidades.entidadprestadora",
                verbose_name="Entidad",
            ),
        ),
        migrations.AddField(
            model_name="normativareferencia",
            name="estandares_relacionados",
            field=models.ManyToManyField(
                blank=True, related_name="normativas", to="estandares.estandar"
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="criterio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompts",
                to="estandares.criterio",
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="entidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompts_personalizados",
                to="entidades.entidadprestadora",
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="estandar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompts",
                to="estandares.estandar",
            ),
        ),
        migrations.AddField(
            model_name="solicitudia",
            name="entidad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_ia",
                to="entidades.entidadprestadora",
            ),
        ),
    ]
