# Generated by Django 6.0.1 on 2026-01-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documentos", "0002_initial"),
        ("evaluacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudia",
            name="evaluacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_ia",
                to="evaluacion.evaluacion",
            ),
        ),
        migrations.AddField(
            model_name="solicitudia",
            name="prompt_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documentos.prompttemplate",
            ),
        ),
    ]
