# Generated by Django 6.0.1 on 2026-01-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estandar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, verbose_name="Código")),
                (
                    "codigo_corto",
                    models.CharField(
                        blank=True,
                        help_text="Código abreviado para uso interno (ej: TSTH, INF, DOT)",
                        max_length=20,
                        verbose_name="Código corto",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "paginas_resolucion",
                    models.CharField(
                        blank=True,
                        help_text="Referencia a páginas en la resolución original",
                        max_length=20,
                        verbose_name="Páginas en resolución",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de presentación"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Estándar",
                "verbose_name_plural": "Estándares",
                "ordering": ["grupo", "orden", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="EstandarServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TH", "Talento Humano"),
                            ("INF", "Infraestructura"),
                            ("DOT", "Dotación"),
                            ("MD", "Medicamentos y Dispositivos"),
                            ("PP", "Procesos Prioritarios"),
                            ("HCR", "Historia Clínica y Registros"),
                            ("INT", "Interdependencia"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de estándar",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código específico del estándar para este servicio (ej: URG_TH)",
                        max_length=30,
                        verbose_name="Código",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Estándar de Servicio",
                "verbose_name_plural": "Estándares de Servicios",
                "ordering": ["servicio", "orden"],
            },
        ),
        migrations.CreateModel(
            name="GrupoEstandar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=10, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "aplica_todos",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este grupo aplica a todos los servicios (como el grupo 11.1)",
                        verbose_name="Aplica a todos los servicios",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de presentación"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Grupo de Estándares",
                "verbose_name_plural": "Grupos de Estándares",
                "ordering": ["orden", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="Criterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Numeración del criterio (ej: 1, 1.1, 1.1.1)",
                        max_length=20,
                        verbose_name="Número",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Texto del criterio")),
                (
                    "es_titulo",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si es un título de sección y no requiere evaluación",
                        verbose_name="Es título/sección",
                    ),
                ),
                (
                    "complejidad_aplica",
                    models.CharField(
                        blank=True,
                        help_text="Indica a qué complejidades aplica (baja, media, alta)",
                        max_length=100,
                        verbose_name="Complejidad aplicable",
                    ),
                ),
                (
                    "modalidad_aplica",
                    models.CharField(
                        blank=True,
                        help_text="Indica a qué modalidades aplica",
                        max_length=200,
                        verbose_name="Modalidad aplicable",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "estandar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios",
                        to="estandares.estandar",
                        verbose_name="Estándar general",
                    ),
                ),
                (
                    "estandar_servicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios",
                        to="estandares.estandarservicio",
                        verbose_name="Estándar de servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Criterio",
                "verbose_name_plural": "Criterios",
                "ordering": ["orden", "numero"],
            },
        ),
        migrations.AddField(
            model_name="estandar",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estandares",
                to="estandares.grupoestandar",
                verbose_name="Grupo",
            ),
        ),
        migrations.CreateModel(
            name="PlantillaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la plantilla"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "contenido_html",
                    models.TextField(
                        blank=True,
                        help_text="Contenido de la plantilla en formato HTML",
                        verbose_name="Contenido HTML",
                    ),
                ),
                (
                    "archivo_plantilla",
                    models.FileField(
                        blank=True,
                        help_text="Archivo Word/PDF de plantilla",
                        null=True,
                        upload_to="plantillas/",
                        verbose_name="Archivo plantilla",
                    ),
                ),
                (
                    "es_ejemplo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si es una plantilla de ejemplo del sistema",
                        verbose_name="Es ejemplo",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas",
                        to="estandares.criterio",
                        verbose_name="Criterio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Documento",
                "verbose_name_plural": "Plantillas de Documentos",
                "ordering": ["criterio", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del servicio"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "codigo_hoja_excel",
                    models.CharField(
                        blank=True,
                        help_text="Referencia a la hoja en el archivo Excel de autoevaluación",
                        max_length=50,
                        verbose_name="Código hoja Excel",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to="estandares.grupoestandar",
                        verbose_name="Grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "ordering": ["grupo", "orden", "codigo"],
            },
        ),
        migrations.AddField(
            model_name="estandarservicio",
            name="servicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estandares_especificos",
                to="estandares.servicio",
                verbose_name="Servicio",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="estandar",
            unique_together={("grupo", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="estandarservicio",
            unique_together={("servicio", "tipo")},
        ),
    ]
