# Generated by Django 6.0.1 on 2026-01-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estandares", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="es_obligatorio",
            field=models.BooleanField(
                default=False,
                help_text="Los servicios del grupo 11.1 son obligatorios para todas las entidades",
                verbose_name="Es obligatorio",
            ),
        ),
    ]
