# Generated by Django 4.2.25 on 2026-01-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estandares", "0002_servicio_es_obligatorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterio",
            name="tipo_criterio",
            field=models.CharField(
                choices=[
                    ("CRITERIO", "Criterio Evaluable"),
                    ("TITULO", "Título de Sección"),
                    ("SUBTITULO", "Subtítulo"),
                    ("NOTA", "Nota o Aclaración"),
                ],
                default="CRITERIO",
                help_text="Indica si es un criterio evaluable, título o subtítulo",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
