# Generated by Django 6.0.1 on 2026-01-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del documento"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "contenido_html",
                    models.TextField(
                        blank=True,
                        help_text="Contenido del documento en formato HTML editable",
                        verbose_name="Contenido editable",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="evaluaciones/documentos/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versión"),
                ),
                (
                    "es_version_final",
                    models.BooleanField(default=False, verbose_name="Es versión final"),
                ),
                (
                    "generado_con_ia",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el documento fue generado o modificado con ayuda de IA",
                        verbose_name="Generado con IA",
                    ),
                ),
                (
                    "prompt_ia",
                    models.TextField(
                        blank=True,
                        help_text="Prompt utilizado para generar el documento con IA",
                        verbose_name="Prompt IA",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Evaluación",
                "verbose_name_plural": "Documentos de Evaluación",
                "ordering": ["evaluacion", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("C", "Cumple"),
                            ("NC", "No Cumple"),
                            ("NA", "No Aplica"),
                            ("PE", "Pendiente de evaluar"),
                        ],
                        default="PE",
                        max_length=5,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "estado_documento",
                    models.CharField(
                        choices=[
                            ("NT", "No Trabajado"),
                            ("ED", "En Desarrollo"),
                            ("AP", "Aprobado"),
                        ],
                        default="NT",
                        max_length=5,
                        verbose_name="Estado del documento",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(blank=True, verbose_name="Comentarios"),
                ),
                (
                    "justificacion_na",
                    models.TextField(
                        blank=True,
                        help_text="Obligatorio cuando el estado es NA",
                        verbose_name="Justificación No Aplica",
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de evaluación"
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True,
                        help_text="Para criterios con documentos que tienen fecha de vencimiento",
                        null=True,
                        verbose_name="Fecha de vencimiento",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
                "ordering": ["sede", "criterio"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREAR", "Creación"),
                            ("EDITAR", "Edición"),
                            ("CAMBIAR_ESTADO", "Cambio de estado"),
                            ("APROBAR", "Aprobación"),
                            ("RECHAZAR", "Rechazo"),
                            ("ASIGNAR", "Asignación de responsable"),
                            ("ADJUNTAR", "Adjuntar documento"),
                            ("COMENTAR", "Agregar comentario"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Estado anterior"
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Estado nuevo"
                    ),
                ),
                (
                    "datos_adicionales",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos adicionales"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
            ],
            options={
                "verbose_name": "Historial de Evaluación",
                "verbose_name_plural": "Historial de Evaluaciones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="PeriodoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del período"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin")),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Período activo"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "porcentaje_cumplimiento_general",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Porcentaje cumplimiento general",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Período de Evaluación",
                "verbose_name_plural": "Períodos de Evaluación",
                "ordering": ["entidad", "-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ResumenCumplimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_criterios",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total criterios"
                    ),
                ),
                (
                    "criterios_cumple",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Criterios que cumplen"
                    ),
                ),
                (
                    "criterios_no_cumple",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Criterios que no cumplen"
                    ),
                ),
                (
                    "criterios_no_aplica",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Criterios no aplica"
                    ),
                ),
                (
                    "criterios_pendientes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Criterios pendientes"
                    ),
                ),
                (
                    "porcentaje_cumplimiento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentaje de cumplimiento",
                    ),
                ),
                (
                    "fecha_calculo",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de cálculo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen de Cumplimiento",
                "verbose_name_plural": "Resúmenes de Cumplimiento",
                "ordering": ["sede", "grupo_estandar", "estandar"],
            },
        ),
    ]
