# Generated by Django 6.0.1 on 2026-01-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0002_initial"),
        ("estandares", "0001_initial"),
        ("evaluacion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoevaluacion",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="criterio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluaciones",
                to="estandares.criterio",
                verbose_name="Criterio",
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluaciones_modificadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="responsable_aprobacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluaciones_aprobacion",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable de aprobación",
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="responsable_calidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluaciones_calidad",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable de calidad",
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="responsable_desarrollo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluaciones_desarrollo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable de desarrollo",
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluaciones",
                to="entidades.sede",
                verbose_name="Sede",
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="servicio_habilitado",
            field=models.ForeignKey(
                blank=True,
                help_text="Solo aplica para criterios de servicios específicos",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluaciones",
                to="entidades.serviciohabilitado",
                verbose_name="Servicio habilitado",
            ),
        ),
        migrations.AddField(
            model_name="documentoevaluacion",
            name="evaluacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="evaluacion.evaluacion",
                verbose_name="Evaluación",
            ),
        ),
        migrations.AddField(
            model_name="historialevaluacion",
            name="evaluacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial",
                to="evaluacion.evaluacion",
                verbose_name="Evaluación",
            ),
        ),
        migrations.AddField(
            model_name="historialevaluacion",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historial_evaluaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="periodoevaluacion",
            name="entidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periodos_evaluacion",
                to="entidades.entidadprestadora",
                verbose_name="Entidad",
            ),
        ),
        migrations.AddField(
            model_name="resumencumplimiento",
            name="estandar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumenes_cumplimiento",
                to="estandares.estandar",
            ),
        ),
        migrations.AddField(
            model_name="resumencumplimiento",
            name="grupo_estandar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumenes_cumplimiento",
                to="estandares.grupoestandar",
            ),
        ),
        migrations.AddField(
            model_name="resumencumplimiento",
            name="periodo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumenes",
                to="evaluacion.periodoevaluacion",
                verbose_name="Período",
            ),
        ),
        migrations.AddField(
            model_name="resumencumplimiento",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumenes_cumplimiento",
                to="entidades.sede",
                verbose_name="Sede",
            ),
        ),
        migrations.AddField(
            model_name="resumencumplimiento",
            name="servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumenes_cumplimiento",
                to="estandares.servicio",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluacion",
            unique_together={("sede", "criterio", "servicio_habilitado")},
        ),
    ]
