# Generated by Django 6.0.1 on 2026-01-14 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0003_configuracionevaluacion"),
        ("estandares", "0002_servicio_es_obligatorio"),
        ("evaluacion", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluacionCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("P", "Pendiente"),
                            ("C", "Cumple"),
                            ("NC", "No Cumple"),
                            ("NA", "No Aplica"),
                        ],
                        default="P",
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "en_proceso",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se está trabajando activamente en este criterio",
                        verbose_name="En proceso",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(blank=True, verbose_name="Comentarios"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_entidad",
                        to="estandares.criterio",
                        verbose_name="Criterio",
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_criterios",
                        to="entidades.entidadprestadora",
                        verbose_name="Entidad",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluaciones_criterios_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="criterios_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de Criterio",
                "verbose_name_plural": "Evaluaciones de Criterios",
                "ordering": ["entidad", "criterio__orden"],
                "unique_together": {("entidad", "criterio")},
            },
        ),
        migrations.CreateModel(
            name="ArchivoRepositorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="repositorio/%Y/%m/", verbose_name="Archivo"
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de subida"
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archivos_subidos_repositorio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos_repositorio",
                        to="evaluacion.evaluacioncriterio",
                        verbose_name="Evaluación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo de Repositorio",
                "verbose_name_plural": "Archivos de Repositorio",
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
