# Generated by Django 4.2.25 on 2026-01-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estandares", "0002_servicio_es_obligatorio"),
        ("entidades", "0004_cambio_evaluacion_sede"),
        ("evaluacion", "0003_evaluacioncriterio_archivorepositorio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evaluacioncriterio",
            options={
                "ordering": ["sede", "criterio__orden"],
                "verbose_name": "Evaluación de Criterio",
                "verbose_name_plural": "Evaluaciones de Criterios",
            },
        ),
        migrations.AlterUniqueTogether(
            name="evaluacioncriterio",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="evaluacioncriterio",
            name="fecha_evaluacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de evaluación"
            ),
        ),
        migrations.AddField(
            model_name="evaluacioncriterio",
            name="justificacion_na",
            field=models.TextField(
                blank=True,
                help_text="Obligatorio cuando el estado es NA",
                verbose_name="Justificación No Aplica",
            ),
        ),
        migrations.AddField(
            model_name="evaluacioncriterio",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluaciones_criterios",
                to="entidades.sede",
                verbose_name="Sede",
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioncriterio",
            name="criterio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluaciones_sede",
                to="estandares.criterio",
                verbose_name="Criterio",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluacioncriterio",
            unique_together={("sede", "criterio")},
        ),
        migrations.RemoveField(
            model_name="evaluacioncriterio",
            name="entidad",
        ),
    ]
