# Generated by Django 4.2.25 on 2026-01-16 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0004_cambio_evaluacion_sede"),
        ("evaluacion", "0004_cambio_evaluacion_sede"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacioncriterio",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluaciones_criterios",
                to="entidades.sede",
                verbose_name="Sede",
            ),
        ),
    ]
