# Generated by Django 6.0.1 on 2026-01-10 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "primer_nombre",
                    models.CharField(max_length=50, verbose_name="Primer nombre"),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Segundo nombre"
                    ),
                ),
                (
                    "primer_apellido",
                    models.CharField(max_length=50, verbose_name="Primer apellido"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Segundo apellido"
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Documento de identidad"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("SUPER", "Super Administrador"),
                            ("ADMIN", "Administrador de Entidad"),
                            ("CALIDAD", "Responsable de Calidad"),
                            ("EVALUADOR", "Evaluador"),
                            ("APROBADOR", "Aprobador"),
                            ("CONSULTOR", "Consultor (Solo lectura)"),
                        ],
                        default="CONSULTOR",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="usuarios/fotos/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "fecha_ultimo_acceso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último acceso"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios",
                        to="entidades.entidadprestadora",
                        verbose_name="Entidad Prestadora",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "sedes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="usuarios",
                        to="entidades.sede",
                        verbose_name="Sedes asignadas",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["primer_apellido", "primer_nombre"],
            },
        ),
        migrations.CreateModel(
            name="RegistroActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Inicio de sesión"),
                            ("LOGOUT", "Cierre de sesión"),
                            ("CREAR", "Creación"),
                            ("EDITAR", "Edición"),
                            ("ELIMINAR", "Eliminación"),
                            ("APROBAR", "Aprobación"),
                            ("RECHAZAR", "Rechazo"),
                            ("EXPORTAR", "Exportación"),
                            ("IMPORTAR", "Importación"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de actividad",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "modelo_afectado",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modelo afectado"
                    ),
                ),
                (
                    "objeto_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID del objeto"
                    ),
                ),
                (
                    "datos_anteriores",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos anteriores"
                    ),
                ),
                (
                    "datos_nuevos",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos nuevos"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de actividad",
                "verbose_name_plural": "Registros de actividad",
                "ordering": ["-fecha"],
            },
        ),
    ]
