# Generated by Django 6.0.1 on 2026-01-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CicloPHVA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("PLANEAR", "Planear"),
                            ("HACER", "Hacer"),
                            ("VERIFICAR", "Verificar"),
                            ("ACTUAR", "Actuar"),
                        ],
                        max_length=20,
                        verbose_name="Fase",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentaje de avance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo PHVA",
                "verbose_name_plural": "Ciclos PHVA",
                "ordering": ["programa", "fase"],
            },
        ),
        migrations.CreateModel(
            name="ProgramaPAMEC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del programa"
                    ),
                ),
                ("periodo", models.CharField(max_length=50, verbose_name="Período")),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANIFICACION", "En Planificación"),
                            ("EJECUCION", "En Ejecución"),
                            ("SEGUIMIENTO", "En Seguimiento"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        default="PLANIFICACION",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa PAMEC",
                "verbose_name_plural": "Programas PAMEC",
                "ordering": ["entidad", "-fecha_inicio"],
            },
        ),
    ]
