# Generated by Django 6.0.1 on 2026-01-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0002_initial"),
        ("pamec", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ciclophva",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ciclos_pamec",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programapamec",
            name="entidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programas_pamec",
                to="entidades.entidadprestadora",
                verbose_name="Entidad",
            ),
        ),
        migrations.AddField(
            model_name="ciclophva",
            name="programa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ciclos",
                to="pamec.programapamec",
                verbose_name="Programa",
            ),
        ),
    ]
